// ===============================================================
// erisml_fsm.cpp
//
// Synthesizable C++ for Vitis HLS targeting Xilinx Alveo U55C.
// Generated by erisml_compiler.silicon.hls_emit (Phase 3 / Track C).
//
// Do not edit by hand; regenerate via:
//     eris-compile silicon-emit --out src/silicon/erisml_fsm.cpp
// ===============================================================

#include <ap_int.h>

extern "C" {
        // ---------------------------------------------------------------
        // Commitment FSM
        // Generated from erisml_compiler.fsm.commitment_fsm by hls_emit.py.
        // Synthesizable for Vitis HLS targeting Xilinx Alveo U55C.
        // ---------------------------------------------------------------

        enum Commitment_State : ap_uint<3> {
    COMMITMENT_ACTIVE = 0,
    COMMITMENT_ACTIVE_BUT_DEFEASIBLE = 1,
    COMMITMENT_DEFEATED = 2,
    COMMITMENT_FULFILLED = 3,
    COMMITMENT_VIOLATED = 4,
    COMMITMENT_VOID = 5,
    COMMITMENT_EXPIRED = 6,
};

        enum Commitment_Event : ap_uint<4> {
    COMMITMENT_EVT_FULFILLING_EVENT = 0,
    COMMITMENT_EVT_VIOLATING_EVENT = 1,
    COMMITMENT_EVT_EXPIRATION_EVENT = 2,
    COMMITMENT_EVT_DEFEASIBILITY_CONDITION_TRIGGERED = 3,
    COMMITMENT_EVT_DEFEASIBILITY_RESOLVED_IN_FAVOR = 4,
    COMMITMENT_EVT_DEFEASIBILITY_OVERRIDES = 5,
    COMMITMENT_EVT_LEGITIMACY_COLLAPSES = 6,
};

        Commitment_State commitment_step(Commitment_State current, Commitment_Event event_tag) {
        #pragma HLS INLINE
        #pragma HLS PIPELINE II=1
            // Terminal states are absorbing.
    if (current == COMMITMENT_DEFEATED || current == COMMITMENT_FULFILLED || current == COMMITMENT_VIOLATED || current == COMMITMENT_VOID || current == COMMITMENT_EXPIRED) return current;

    switch (current) {
    case COMMITMENT_ACTIVE:
        switch (event_tag) {
        case COMMITMENT_EVT_DEFEASIBILITY_CONDITION_TRIGGERED: return COMMITMENT_ACTIVE_BUT_DEFEASIBLE;
        case COMMITMENT_EVT_FULFILLING_EVENT: return COMMITMENT_FULFILLED;
        case COMMITMENT_EVT_VIOLATING_EVENT: return COMMITMENT_VIOLATED;
        case COMMITMENT_EVT_LEGITIMACY_COLLAPSES: return COMMITMENT_VOID;
        case COMMITMENT_EVT_EXPIRATION_EVENT: return COMMITMENT_EXPIRED;
        default: return current;
        }
    case COMMITMENT_ACTIVE_BUT_DEFEASIBLE:
        switch (event_tag) {
        case COMMITMENT_EVT_DEFEASIBILITY_RESOLVED_IN_FAVOR: return COMMITMENT_ACTIVE;
        case COMMITMENT_EVT_DEFEASIBILITY_OVERRIDES: return COMMITMENT_DEFEATED;
        case COMMITMENT_EVT_VIOLATING_EVENT: return COMMITMENT_VIOLATED;
        case COMMITMENT_EVT_FULFILLING_EVENT: return COMMITMENT_FULFILLED;
        case COMMITMENT_EVT_LEGITIMACY_COLLAPSES: return COMMITMENT_VOID;
        case COMMITMENT_EVT_EXPIRATION_EVENT: return COMMITMENT_EXPIRED;
        default: return current;
        }
    default: return current;
    }
        }

        // ---------------------------------------------------------------
        // Legitimacy FSM
        // Generated from erisml_compiler.fsm.legitimacy_fsm by hls_emit.py.
        // Synthesizable for Vitis HLS targeting Xilinx Alveo U55C.
        // ---------------------------------------------------------------

        enum Legitimacy_State : ap_uint<3> {
    LEGITIMACY_FULLY_LEGITIMATE = 0,
    LEGITIMACY_DEFEASIBLE = 1,
    LEGITIMACY_COERCIVE = 2,
    LEGITIMACY_TYRANNICAL = 3,
    LEGITIMACY_FRAUDULENT = 4,
    LEGITIMACY_VOID = 5,
};

        enum Legitimacy_Event : ap_uint<4> {
    LEGITIMACY_EVT_PROCEDURAL_VIOLATION = 0,
    LEGITIMACY_EVT_COERCION_DETECTED = 1,
    LEGITIMACY_EVT_RESTORED = 2,
    LEGITIMACY_EVT_ESCALATES = 3,
    LEGITIMACY_EVT_CATASTROPHIC_INTENT = 4,
    LEGITIMACY_EVT_EVIDENCE_REVEALED = 5,
};

        Legitimacy_State legitimacy_step(Legitimacy_State current, Legitimacy_Event event_tag) {
        #pragma HLS INLINE
        #pragma HLS PIPELINE II=1
            // Terminal states are absorbing.
    if (current == LEGITIMACY_VOID) return current;

    switch (current) {
    case LEGITIMACY_FULLY_LEGITIMATE:
        switch (event_tag) {
        case LEGITIMACY_EVT_PROCEDURAL_VIOLATION: return LEGITIMACY_DEFEASIBLE;
        case LEGITIMACY_EVT_COERCION_DETECTED: return LEGITIMACY_COERCIVE;
        case LEGITIMACY_EVT_EVIDENCE_REVEALED: return LEGITIMACY_FRAUDULENT;
        default: return current;
        }
    case LEGITIMACY_DEFEASIBLE:
        switch (event_tag) {
        case LEGITIMACY_EVT_RESTORED: return LEGITIMACY_FULLY_LEGITIMATE;
        case LEGITIMACY_EVT_COERCION_DETECTED: return LEGITIMACY_COERCIVE;
        case LEGITIMACY_EVT_EVIDENCE_REVEALED: return LEGITIMACY_FRAUDULENT;
        default: return current;
        }
    case LEGITIMACY_COERCIVE:
        switch (event_tag) {
        case LEGITIMACY_EVT_ESCALATES: return LEGITIMACY_TYRANNICAL;
        case LEGITIMACY_EVT_CATASTROPHIC_INTENT: return LEGITIMACY_VOID;
        default: return current;
        }
    case LEGITIMACY_TYRANNICAL:
        switch (event_tag) {
        case LEGITIMACY_EVT_CATASTROPHIC_INTENT: return LEGITIMACY_VOID;
        default: return current;
        }
    case LEGITIMACY_FRAUDULENT:
        switch (event_tag) {
        case LEGITIMACY_EVT_EVIDENCE_REVEALED: return LEGITIMACY_VOID;
        default: return current;
        }
    default: return current;
    }
        }

        // ---------------------------------------------------------------
        // Consent FSM
        // Generated from erisml_compiler.fsm.consent_fsm by hls_emit.py.
        // Synthesizable for Vitis HLS targeting Xilinx Alveo U55C.
        // ---------------------------------------------------------------

        enum Consent_State : ap_uint<3> {
    CONSENT_NOT_OBTAINED = 0,
    CONSENT_OBTAINED = 1,
    CONSENT_COERCED = 2,
    CONSENT_WITHDRAWN = 3,
};

        enum Consent_Event : ap_uint<4> {
    CONSENT_EVT_CONSENT_GIVEN = 0,
    CONSENT_EVT_COERCED_ASSENT = 1,
    CONSENT_EVT_WITHDRAWN = 2,
    CONSENT_EVT_COERCED_REVISIT = 3,
};

        Consent_State consent_step(Consent_State current, Consent_Event event_tag) {
        #pragma HLS INLINE
        #pragma HLS PIPELINE II=1
            // Terminal states are absorbing.
    if (current == CONSENT_COERCED || current == CONSENT_WITHDRAWN) return current;

    switch (current) {
    case CONSENT_NOT_OBTAINED:
        switch (event_tag) {
        case CONSENT_EVT_CONSENT_GIVEN: return CONSENT_OBTAINED;
        case CONSENT_EVT_COERCED_ASSENT: return CONSENT_COERCED;
        default: return current;
        }
    case CONSENT_OBTAINED:
        switch (event_tag) {
        case CONSENT_EVT_WITHDRAWN: return CONSENT_WITHDRAWN;
        case CONSENT_EVT_COERCED_REVISIT: return CONSENT_COERCED;
        default: return current;
        }
    default: return current;
    }
        }

}  // extern "C"
